openapi: 3.1.0
info:
  title: Van Nav API
  description: Van Nav 导航系统的 API 文档
  version: 1.0.0

servers:
  - url: http://localhost:6412
    description: 开发环境服务器

components:
  schemas:
    Tool:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        logo:
          type: string
        desc:
          type: string
        catelogId:
          type: integer

    AddToolDto:
      type: object
      required:
        - name
        - url
      properties:
        name:
          type: string
        url:
          type: string
        logo:
          type: string
        desc:
          type: string
        catelogId:
          type: integer

    UpdateToolDto:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        name:
          type: string
        url:
          type: string
        logo:
          type: string
        desc:
          type: string
        catelogId:
          type: integer

    Catelog:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        desc:
          type: string

    UpdateCatelogDto:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        name:
          type: string
        desc:
          type: string

    Setting:
      type: object
      properties:
        title:
          type: string
        logo192:
          type: string
        logo512:
          type: string

    LoginDto:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string

    UpdateUserDto:
      type: object
      required:
        - name
        - password
      properties:
        name:
          type: string
        password:
          type: string

    ApiToken:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        value:
          type: string
        disabled:
          type: integer

    AddTokenDto:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    StandardResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        errorMessage:
          type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /api/login:
    post:
      security: []
      summary: 用户登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "200":
          description: 登录成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/StandardResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          user:
                            type: object
                          token:
                            type: string

  /api/logout:
    get:
      security: []
      summary: 用户登出
      responses:
        "200":
          description: 登出成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/:
    get:
      security: []
      summary: 获取所有数据
      responses:
        "200":
          description: 成功获取所有数据
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/StandardResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          tools:
                            type: array
                            items:
                              $ref: "#/components/schemas/Tool"
                          catelogs:
                            type: array
                            items:
                              $ref: "#/components/schemas/Catelog"
                          setting:
                            $ref: "#/components/schemas/Setting"

  /api/admin/all:
    get:
      summary: 管理员获取所有数据
      security:
        - BearerAuth: []
      responses:
        "200":
          description: 成功获取所有数据
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/StandardResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          tools:
                            type: array
                            items:
                              $ref: "#/components/schemas/Tool"
                          catelogs:
                            type: array
                            items:
                              $ref: "#/components/schemas/Catelog"
                          setting:
                            $ref: "#/components/schemas/Setting"
                          user:
                            type: object
                            properties:
                              name:
                                type: string
                              id:
                                type: string
                          tokens:
                            type: array
                            items:
                              $ref: "#/components/schemas/ApiToken"

  /api/admin/exportTools:
    get:
      summary: 导出所有工具
      security:
        - BearerAuth: []
      responses:
        "200":
          description: 成功导出工具列表
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/StandardResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/Tool"

  /api/admin/importTools:
    post:
      summary: 导入工具列表
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Tool"
      responses:
        "200":
          description: 导入成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/img:
    get:
      security: []
      summary: 获取 logo 图片
      parameters:
        - name: url
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功获取图片
          content:
            image/*:
              schema:
                type: string
                format: binary

  /manifest.json:
    get:
      security: []
      summary: 获取 PWA manifest
      responses:
        "200":
          description: 成功获取 manifest
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_name:
                    type: string
                  name:
                    type: string
                  icons:
                    type: array
                    items:
                      type: object
                      properties:
                        src:
                          type: string
                        type:
                          type: string
                        sizes:
                          type: string
                  start_url:
                    type: string
                  display:
                    type: string
                  scope:
                    type: string
                  theme_color:
                    type: string
                  background_color:
                    type: string

  /api/admin/tool:
    post:
      summary: 添加新工具
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddToolDto"
      responses:
        "200":
          description: 添加成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/tool/{id}:
    delete:
      summary: 删除工具
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

    put:
      summary: 更新工具
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateToolDto"
      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/catelog:
    post:
      summary: 添加新分类
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                desc:
                  type: string
      responses:
        "200":
          description: 添加分类成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/catelog/{id}:
    delete:
      summary: 删除分类
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 删除分类成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

    put:
      summary: 更新分类
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateCatelogDto"
      responses:
        "200":
          description: 更新分类成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/apiToken:
    post:
      summary: 添加 API Token
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddTokenDto"
      responses:
        "200":
          description: 添加 Token 成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/StandardResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          id:
                            type: string
                          value:
                            type: string
                          name:
                            type: string

  /api/admin/apiToken/{id}:
    delete:
      summary: 删除 API Token
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 删除 Token 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/setting:
    put:
      summary: 更新系统设置
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Setting"
      responses:
        "200":
          description: 更新设置成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/user:
    put:
      summary: 更新用户信息
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserDto"
      responses:
        "200":
          description: 更新用户信息成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"

  /api/admin/tools/sort:
    put:
      summary: 批量更新工具排序
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  sort:
                    type: integer
      responses:
        "200":
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StandardResponse"
        "400":
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
security:
  - BearerAuth: []
